### ISSUE TITLE
Short-term Plan

### ISSUE THREAD

**Issue by zw0610** [caicloud/ftlib#19]
# Short-term Plan

**!!!This issue is still under edit**

The ultimate goal of `FTLib` is to keep a distributed training continue after a lost or join of a worker.

## Status Quo

The most recent example shows we can add/remove worker for a `PyTorch` distributed training with the consensus protocol of `shared_storage`, which asks for a shared storage across all participating workers.

## Short-term Goals

For `Consensus` part, we aimed to get rid of the shared storage. Therefore, we plan to add gossip-based consensus protocol.

~~For `Framework` ( we may rename it to `Communication`) part, TesorFlow will also be supported along with PyTorch.~~

For `FTLib` part, we will refactor again after a refresh of design docs.

## Steps

1. add gossip-based consensus
2. refresh design docs
3. refactor code according to the most recent design docs
~~4. add tensorflow support~~
5. setup python package structure
6. setup ci

## TBD

1. TF (eager mode) support
2. reimplement gossip-based consensus in python (so `new_member_join` can notify `FTLib` actively)

**Comment by ddysher** [comment]
can we translate this into a ROADMAP file or something?

**Comment by zw0610** [comment]
ROADMAP added and all steps were taken. /close
