### ISSUE TITLE
BasicFTLib does not have `barrier()` and `broadcast()` methods

### ISSUE THREAD

**Issue by terrytangyuan** [caicloud/ftlib#48]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

In this example, https://github.com/caicloud/ftlib/blob/master/test/kubernetes/script/main.py#L138-L141, we are using these two methods from `ftlib` instance but these methods do not exist in `BasicFTLib` class.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by zw0610** [comment]
These two methods are already registered to `BasicFTLib` with decorator: https://github.com/caicloud/ftlib/blob/master/ftlib/commlib/pytorch/impl.py#L54

decorator implementation part 1: https://github.com/caicloud/ftlib/blob/master/ftlib/commlib/basic_commlib.py#L8

decorator implementation part 2:
https://github.com/caicloud/ftlib/blob/master/ftlib/impl.py#L97

**Comment by terrytangyuan** [comment]
Got it. I wonder if there’s a way to make it IDE-friendly.
