### ISSUE TITLE
Support broadcast operation

### ISSUE THREAD

**Issue by terrytangyuan** [caicloud/ftlib#5]
As proposed in the design doc here: https://github.com/sql-machine-learning/elasticdl/blob/140491358168ee202e013e0bd2c8b8f8ddfd46d2/docs/designs/allreduce.md#fault-tolerant-allreduce-implementation

See discussion in https://github.com/sql-machine-learning/elasticdl/pull/1420#discussion_r344996292

/kind feature

**Comment by zw0610** [comment]
Hi Terry, after reviewing the design docs, do you think we should expose the broadcast and barrier API as member functions of `FTLib` or `FTLib.Framework`?

For me, I'd like to have these basic collective APIs as member functions of `FTLib.Framework` while provide `FTLib` with a higher level API like `average_gradient(model=model, sync=True)`.

**Comment by terrytangyuan** [comment]
@zw0610 Yes, I think we should expose both low and high levels APIs.
