### ISSUE TITLE
panic: Failed to create memberlist

### ISSUE THREAD

**Issue by terrytangyuan** [caicloud/ftlib#64]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

```
log file: /tmp/memberlist.log
panic: Failed to create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided

goroutine 17 [running, locked to thread]:
main.init_memberlist(0x7fe8cbf90600, 0x0)
	/root/ftlib/ftlib/consensus/gossip/memberlist/main.go:41 +0x245
main._cgoexpwrap_fc57e92fce6d_init_memberlist(0x7fe8cbf90600, 0x11090e0)
	_cgo_gotypes.go:78 +0x2d
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
* Clone https://github.com/sql-machine-learning/elasticdl/tree/allreduce-test
* Run the following command
```
docker build --target dev -t elasticdl:dev -f elasticdl/docker/Dockerfile .
docker build --target ci -t elasticdl:ci -f elasticdl/docker/Dockerfile .
docker build -t elasticdl:dev_allreduce -f elasticdl/docker/Dockerfile.dev_allreduce .

python3 -m elasticdl.python.elasticdl.client train \
  --image_base=elasticdl:dev_allreduce \
  --docker_image_repository=reg.docker.replace-with-your-registry-here.com/yuantang/ \
  --model_zoo=model_zoo \
  --model_def=deepfm_functional_api.deepfm_functional_api.custom_model \
  --training_data=/data/frappe/train \
  --validation_data=/data/frappe/test \
  --num_epochs=1 \
  --master_resource_request="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
  --master_resource_limit="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
  --worker_resource_request="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
  --worker_resource_limit="cpu=1,memory=4096Mi,ephemeral-storage=10240Mi" \
  --minibatch_size=64 \
  --num_minibatches_per_task=2 \
  --num_workers=2 \
  --checkpoint_steps=500 \
  --evaluation_steps=500 \
  --grads_to_wait=1 \
  --job_name=test-train \
  --log_level=INFO \
  --image_pull_policy=Always \
  --output=/saved_model/model_output \
  --volume="host_path=${PWD},mount_path=/saved_model" \
   --namespace=<replace-by-your-namespace-here> \
  --distribution_strategy=AllreduceStrategy

kub logs elasticdl-test-train-worker-1
```
**Anything else we need to know?**:
Relevant code:
* This is how we wrap FTLib for ElasticDL to use: https://github.com/sql-machine-learning/elasticdl/blob/develop/elasticdl/python/collective_ops/communicator.py
* This is where the wrapped FTLib ops are being used: https://github.com/sql-machine-learning/elasticdl/blob/develop/elasticdl/python/worker/worker.py#L793

**Comment by terrytangyuan** [comment]
@zw0610 If you'd like to put worker pods to sleep, refer this change: https://github.com/sql-machine-learning/elasticdl/commit/6b6f1aa13cb3a463a5d0b74588bc38dfa88402a5

**Comment by terrytangyuan** [comment]
I am seeing a different error when testing on Minikube on Travis: https://travis-ci.org/github/sql-machine-learning/elasticdl/builds/666366309
```
log file: /tmp/memberlist.log
joining with ips:
10.111.2.235
panic: Failed to join cluster: 2 errors occurred:
	* Failed to resolve : lookup : no such host
	* Failed to join 10.111.2.235: dial tcp 10.111.2.235:7946: connect: connection refused
goroutine 17 [running, locked to thread]:
main.join(0x7fc730032450, 0x1, 0x1, 0x7fc6eb4a6c98)
	/root/ftlib/ftlib/consensus/gossip/memberlist/main.go:57 +0x335
main._cgoexpwrap_fc57e92fce6d_join(0x7fc730032450, 0x1, 0x1, 0xc)
	_cgo_gotypes.go:91 +0x41
```

**Comment by zw0610** [comment]
The headless service returns the IP address of the other pod. But code is
not running on that one. So the joining steps failed. You might change
number of workers to 1 if possible. Otherwise, make sure the other pod is
also running the script. Or maybe you can try the simple example on the
readme file in memberlist repo.

**Comment by terrytangyuan** [comment]
@zw0610 There is only 1 worker in this test case though.

**Comment by zw0610** [comment]
After discussing the issue with expert in network, it seems the pod ip address is excluded when getting private ip. https://github.com/hashicorp/go-sockaddr/blob/c7188e74f6acae5a989bdc959aa779f8b9f42faf/ifaddrs.go#L305

**Comment by zw0610** [comment]
Let me update the issue. It seems some cluster configuration prevents the memberlist module from getting a valid private ip when the bind address is set as 0.0.0.0 by default.

It was addressed by specifying the bind addr to the pod ip (see pr #65).

Really appreciate the help from our expert in network @hanxueluo

**Comment by terrytangyuan** [comment]
Thank you @zw0610 and @hanxueluo! I can verify that #65 fixes the issue. Closing this for now.

**Comment by terrytangyuan** [comment]
@zw0610 Seems like I am getting this error in our internal cluster in case of two workers. For one worker case it seems fine. I double checked that this pod has exposed the port `7946`. Anything else I am missing here?

```
>>> from ftlib.consensus.gossip import Gossip; a=Gossip(None, ['11.161.60.215'], custom_bind_addr="11.238.113.75")
log file: /tmp/memberlist.log
joining with ips:
11.161.60.215
panic: Failed to join cluster: 2 errors occurred:
	* Failed to resolve : lookup : no such host
	* Failed to join 11.161.60.215: dial tcp 11.161.60.215:7946: connect: connection refused

goroutine 17 [running, locked to thread]:
main.join(0x7f96c3150cd0, 0x1, 0x1, 0x7f96c21f7c38)
	/root/ftlib/ftlib/consensus/gossip/memberlist/main.go:71 +0x335
main._cgoexpwrap_0a14e1e91af3_join(0x7f96c3150cd0, 0x1, 0x1, 0xc)
	_cgo_gotypes.go:91 +0x41
```

**Comment by zw0610** [comment]
Before joining with ip of 11.161.60.215, we need to make sure the pod with ip addr of 11.161.60.215 has set up a Gossip instance or also trying to initialize a Gossip instance with joining ip 11.238.113.75
