### ISSUE TITLE
Error in building memberlist/main.so

### ISSUE THREAD

**Issue by skydoorkai** [caicloud/ftlib#67]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
```
# command-line-arguments
./main.go:47:41: invalid operation: cTCPTimeout * time.Second (mismatched types _Ctype_int and time.Duration)
cp: cannot stat './memberlist/main.so': No such file or directory
```

**What you expected to happen**:
No error in compiling

**How to reproduce it (as minimally and precisely as possible)**:

cd /root/ftlib/ftlib/consensus/gossip && bash ./gen_shared_lib.sh

**Anything else we need to know?**:
None

**Comment by terrytangyuan** [comment]
Yes @zw0610 is looking into this.

**Comment by terrytangyuan** [comment]
This is now resolved.
/close
